name: Build and test

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --configuration Release
      working-directory: Joonasw.AadTestingDemo.IntegrationTests
      env:
        IntegrationTest__KeyVaultUrl: ${{ secrets.KEY_VAULT_URL }}
        Authentication__Authority: ${{ secrets.API_AUTHORITY }}
        Authentication__AuthorizationUrl: ${{ secrets.API_AUTHORIZATION_URL }}
        Authentication__ClientId: ${{ secrets.API_CLIENT_ID }}
        Authentication__ApplicationIdUri: ${{ secrets.API_APP_ID_URI }}
        AzureServicesAuthConnectionString: ${{ format('RunAs=App;AppId={0};AppKey={1};TenantId={2}', secrets.AZURE_CREDENTIALS.clientId, secrets.AZURE_CREDENTIALS.clientSecret, secrets.AZURE_CREDENTIALS.tenantId) }}
